name: Playwright Tests

on:
  push:
    branches: [master]

permissions: read-all|write-all

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/master'

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
          restore-keys: |
            ${{ runner.os }}-docker-
            
      - uses: actions/setup-node@v2
        with:
          node-version: 16.*

      - run: docker build . --file Dockerfile.focal -t plimage

      - run: docker run -d --name plcontainer plimage

      - run: docker cp plcontainer:./tests/allure-results allure-results

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results

      - uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
