name: Playwright Tests

on:
  push:
    branches: [master]

jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.*
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile.focal -t plimage:latest
      - name: Run Docker container
        run: |
          docker run -d --name plcontainer plimage:latest
      - name: Copy Allure results
        run: sudo docker cp plcontainer:./tests/allure-results allure-results
      - uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results
      - name: Checkout gh-pages branch
        if: always()
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
          continue-on-error: true
      - name: Create Allure report
        if: always()
        id: allure-report
        uses: simple-elf/allure-report-action@master
        with:
          allure-results: allure-results
          gh-pages: gh-pages
          allure-report: allure-report
          allure-history: allure-history
      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_dir: ./gh-pages
          publish_branch: gh-pages
